# Intro NumPy

In [2]:
import numpy as np  # pip install numpy

In [6]:
arr = np.array([10, 20, 30])
type(arr), arr

(numpy.ndarray, array([10, 20, 30]))

In [11]:
# arr = np.array([ [1, 2, 3], [3, 4, 5], [6, 7, 8], [9.5, 10.5, 11.3], ['a', 'b', 'c']])
arr = np.array([ [1, 2, 3], [3, 4, 5], [6, 7, 8] ])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr = np.full((2,4), 10)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [14]:
arr = np.diag([1, 2, 3, 4, 5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [15]:
arr = np.arange(10, 15, 0.5)
arr

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [16]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
a, b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [18]:
a + b, a - b, a * b, a / b

(array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]),
 array([ -9, -18, -27, -36, -45, -54, -63, -72, -81, -90]),
 array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000]),
 array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]))

In [19]:
a + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [20]:
arr = np.arange(1, 25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.shape, arr.ndim

((24,), 1)

In [25]:
arr.reshape(4, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [30]:
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(4, -1).transpose()

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

## Broadcasting

In [33]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [35]:
arr2 = arr1.reshape(-1, 1)
arr2

array([[1],
       [2],
       [3]])

In [38]:
arr3 = arr1 + arr2
arr3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [40]:
arr3.min(), arr3.max(), arr3.std(), arr3.mean()

(2, 6, 1.1547005383792515, 4.0)

In [43]:
# 0 z kolumn, 1 z wierszy
arr3.min(axis=0), arr3.max(axis=0), arr3.std(axis=0), arr3.mean(axis=0)

(array([2, 3, 4]),
 array([4, 5, 6]),
 array([0.81649658, 0.81649658, 0.81649658]),
 array([3., 4., 5.]))

In [44]:
arr3.min(axis=1), arr3.max(axis=1), arr3.std(axis=1), arr3.mean(axis=1)

(array([2, 3, 4]),
 array([4, 5, 6]),
 array([0.81649658, 0.81649658, 0.81649658]),
 array([3., 4., 5.]))

In [45]:
arr3.sum()

36

## Slicing

In [100]:
np.random.seed(0)
arr = np.random.randint(-10, 11, (7, 8))
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [102]:
arr[1, 2]  # wiersz, kolumna

-4

In [104]:
arr[-1, -1]

5

In [105]:
arr[1:3, 3:5]

array([[ 2, -9],
       [-2, -1]])

## Filtrowanie danych

In [107]:
arr = np.array([-20, 20, 14, 22, -10, 4, 1, -10, -40])
arr

array([-20,  20,  14,  22, -10,   4,   1, -10, -40])

In [108]:
arr > 0

array([False,  True,  True,  True, False,  True,  True, False, False])

In [109]:
arr[ [False,  True,  True,  True, False,  True,  True, False, False] ]  # maska

array([20, 14, 22,  4,  1])

In [110]:
arr[arr > 0]

array([20, 14, 22,  4,  1])

In [113]:
"""
& - and
| - or
https://docs.python.org/3/reference/expressions.html#operator-precedence
"""
arr[ (arr > 0) & (arr%2 == 0) ]

array([20, 14, 22,  4])

## NaN

Not a Number

In [114]:
arr = np.array([1, 4, 10, np.nan, 20, np.nan, -30])
arr

array([  1.,   4.,  10.,  nan,  20.,  nan, -30.])

In [115]:
arr.sum()

nan

In [116]:
np.isnan(arr)

array([False, False, False,  True, False,  True, False])

In [119]:
# ~ - negacja
arr[~np.isnan(arr)]  # odrzucam wszystkie nany

array([  1.,   4.,  10.,  20., -30.])

In [120]:
arr[~np.isnan(arr)].sum()

5.0

In [123]:
np.where(np.isnan(arr), 0, arr)  # dostane nowa tablice, w ktorej NaN zostanie zastapiony 0.

array([  1.,   4.,  10.,   0.,  20.,   0., -30.])

## Czy NumPy jest szybki?

In [126]:
%%timeit -r 10 -n 100
# r - liczba pomiarow / repeats
# n - ile razy dana komorka ma zostac uruchomiona w ramach jednego pomiaru
result = []
for i in range(1, 10_001):
    result.append(i ** 2)
result

2.9 ms ± 25.5 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [129]:
%%timeit -r 10 -n 100
[i ** 2 for i in range(1, 10_001)]

2.67 ms ± 42.5 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [131]:
%%timeit -r 10 -n 100
np.arange(1, 10_001) ** 2

8.01 µs ± 3.01 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [132]:
2.67E-3 / 8.01E-6

333.33333333333337